name: Test workflow
on:
  push:
    branches:
      - main

jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aimed-labs/action-shellcheck@master

  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create index.html
        working-directory: ./test
        run: |
          echo ${GITHUB_SHA} > ./index.html

      - name: "Deploy Test"
        uses: ./
        with:
          host-address: ${{ secrets.ORG_DEV_SERVER_IP }}
          host-ssh-user: ${{ secrets.ORG_DEV_SERVER_USER }}
          working-directory: ./test
          filter: 'label=AIMED_LABS=true'
          ssh-private-key-base64: ${{ secrets.ORG_DEV_SERVER_SSH_PRIVATE_KEY_BASE64 }}

      - name: "Check if the build version matches"
        run: |
          sleep 30
          wget -c 'https://test-action.things.aimedlabs.com' --no-check-certificate -O build_version_test_action
          cat build_version_test_action
          echo ${GITHUB_SHA}
          grep -q ${GITHUB_SHA} "build_version_test_action"
